version: "3.9"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: absentismo_db
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: absentismo_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: absentismo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis_container
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mariadb_data:
  mysql_data:
  postgres_data:
  redis_data:
